import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Avatar from '@atlaskit/avatar'
import DropDown from '@atlaskit/icon/glyph/chevron-down'
import Search from '@atlaskit/icon/glyph/editor/search'
import Menu from '@atlaskit/icon/glyph/menu-expand';
import WhatsApp from '../public/whatsApp.svg'
import Logo from '../public/teleport.svg';
import List from '@/components/List'

export default function Home() {
  const data = ["PROCESSING", "PROCESSED", "AT EMBASSY/VFS", "APPROVED", "REJECTED", "FORM COMPLETED"]
  const appearance = ["moved","moved","new","success","removed",""]
  return (
    <>
      <Head>
        <title>Teleport</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <nav className={styles.nav}>
          <div className={styles.logo}>
            <Menu/>
            <Image src={Logo} alt='avatar'/>
          </div>
            <div className={styles.avatarCont}>
              <div className={styles.avatar} >
                <Avatar size="small" />
              </div>
              <span className={styles.avatarText}>
                Hi, Traveller
              </span>
              <DropDown />
            </div>
        </nav>
        <div className={styles.container}>
          <div className={styles.welcome}>
            Welcome to Teleport!
          </div>
          <div className={styles.search}>
            <input type="search" placeholder='Search by name, country' />
            <button className={styles.searchBtn} title='Search'><Search /></button>
          </div>
          <div className={styles.submitted}>
            <div className={styles.application}>
              Submitted applications ({data.length})
            </div>
            {data.map((item, index) => {
              return <List data={item} appearance={appearance[index]} key={index}/>
            })}
          </div>
        </div>
        <div className={styles.whatsApp}>
          <Image src={WhatsApp} width={25} height={25} alt='whatsApp' />
          <span>Ask for help</span>
          </div>
      </main>
    </>
  )
}
